language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"
env:
  - SPHINX=">=1.3,<1.4"
  - SPHINX=">=1.4,<1.5"
  - SPHINX=">=1.5,<1.6"
  - SPHINX=">=1.6,<1.7"
  - SPHINX=">=1.7,<1.8"
install:
  # Install dev requirements
  - pip install -r dev-requirements.txt
  # Limit Sphinx version re: test matrix
  - pip install "sphinx$SPHINX"
  # Sanity/debug-friendliness: list what got installed
  - pip list --format=columns
  # Dev tooling sanity test: can invoke list tasks?
  - inv --list
script:
  - inv travis.blacken
  - flake8
  # Does our own dogfooding website build ok? :D
  - inv docs
